server:
  port: 8888

spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: BookService
            uri: http://book-service:9001
            predicates:
            - Path=/api/v1/books/**
          - id: EmployeeService
            uri: http://employee-service:9010
            predicates:
            - Path=/api/v1/employees/**
          - id: BorrowingService
            uri: http://borrowing-service:9020
            predicates:
            - Path=/api/v1/borrowings/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
          allowedHeaders: "*"


